name: helm-upgrade

run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'Environment to deploy to'
        type: string
      version:
        required: true
        description: 'Version of the image to deploy'
        type: string
      helm-values-path:
        description: 'Path to the helm values file'
        type: string
        default: './helm-charts/todoapp/values.yaml'

jobs:
  helm-deploy:
    runs-on: ubuntu-latest
    name: Helm Deploy
    environment: development
    steps:
      - name: Set Up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Download Helm Artifacts
        uses: actions/download-artifact@v4
        with:
          name: helm-artifacts
          path: .

      - name: Download Python Artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-artifacts
          path: python-artifacts

      - name: Set Up Kubectl
        uses: azure/setup-kubectl@v4

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: todoapp
          config: cluster.yml

      - name: Helm Install Dry Run
        run: helm install todoapp ./helm-charts/todoapp/ --dry-run

      - name: Helm Install
        run: |
          helm upgrade --install todoapp ./helm-charts/todoapp/ \
            --atomic --wait --timeout 3600s --debug \
            -f ${{ inputs.helm-values-path }} \
            --set mysql.configs.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            --set mysql.configs.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
            --set mysql.configs.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
            --set todoapp.secrets.DB_NAME="${{ secrets.DB_NAME }}" \
            --set todoapp.secrets.DB_USER="${{ secrets.DB_USER }}" \
            --set todoapp.secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            --set todoapp.secrets.DB_HOST="${{ secrets.DB_HOST }}" \
            --set todoapp.secrets.SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --set todoapp.image.version="${{ github.sha }}"
